{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "synstream-manager.fullname" . }}
  labels:
    {{- include "synstream-manager.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "synstream-manager.fullname" . }}
  labels:
    {{- include "synstream-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "synstream-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "synstream-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}