{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synstream-operator.fullname" . }}-metrics-service
  namespace: {{ include "synstream-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    {{- include "synstream-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
    {{- include "synstream-operator.selectorLabels" . | nindent 4 }}
{{- end }}