{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "synstream-operator.fullname" . }}-manager-role
  labels:
    {{- include "synstream-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synstream.rtsinv.com
  resources:
  - flows
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synstream.rtsinv.com
  resources:
  - flows/finalizers
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - synstream.rtsinv.com
  resources:
  - flows/status
  - licenses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "synstream-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "synstream-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "synstream-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "synstream-operator.serviceAccountName" . }}
  namespace: {{ include "synstream-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "synstream-operator.fullname" . }}-leader-election-role
  namespace: {{ include "synstream-operator.namespace" . }}
  labels:
    {{- include "synstream-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "synstream-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "synstream-operator.namespace" . }}
  labels:
    {{- include "synstream-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "synstream-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "synstream-operator.serviceAccountName" . }}
  namespace: {{ include "synstream-operator.namespace" . }}
{{- end }}